/**
 * Auto-generate imports for routes.ts
 * This script finds all files with @page and @component decorators
 * and generates the import statements automatically
 */

const fs = require('fs');
const path = require('path');
const glob = require('glob');

/**
 * Check if a file contains a specific decorator
 */
function hasDecorator(filePath, decoratorName) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const regex = new RegExp(`@${decoratorName}\\s*\\(`);
  return regex.test(content);
}

/**
 * Generate import statement from file path
 */
function generateImport(filePath) {
  // Convert absolute to relative path from routes.ts
  const relativePath = './' + path.relative('src', filePath).replace(/\\/g, '/').replace(/\.ts$/, '');
  return `import "${relativePath}";`;
}

/**
 * Generate the imports section for routes.ts
 */
function generateImports() {
  // Find all TypeScript files in pages and components
  const pageFiles = glob.sync('./src/pages/**/*.ts');
  const componentFiles = glob.sync('./src/components/**/*.ts');

  // Filter files that have decorators
  const pagesWithDecorator = pageFiles.filter(f => hasDecorator(f, 'page'));
  const componentsWithDecorator = componentFiles.filter(f => hasDecorator(f, 'component'));

  // Generate import statements
  const pageImports = pagesWithDecorator.map(generateImport);
  const componentImports = componentsWithDecorator.map(generateImport);

  return {
    pageImports: pageImports.sort(),
    componentImports: componentImports.sort(),
    stats: {
      pages: pageImports.length,
      components: componentImports.length
    }
  };
}

/**
 * Generate the complete routes.ts file
 */
function generateRoutesFile() {
  const { pageImports, componentImports, stats } = generateImports();

  const template = `/**
 * Route Dispatcher & Module Registry
 * Central location for all pages and components auto-discovery
 *
 * ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: generate-imports.js
 * Run: npm run generate:routes
 *
 * https://engine.sygnal.com/
 *
 * ENGINE MODE
 * ?engine.mode=dev
 * ?engine.mode=prod
 */

import { RouteDispatcher } from "@sygnal/sse";
import { Site } from "./site";
import { getAllPages, getComponent, getRegistryStats } from "./engine/registry";

// ============================================================
// PAGES - Auto-discovered (${stats.pages} found)
// ============================================================
${pageImports.join('\n')}

// ============================================================
// COMPONENTS - Auto-discovered (${stats.components} found)
// ============================================================
${componentImports.join('\n')}

/**
 * Create and configure route dispatcher
 */
export const routeDispatcher = (): RouteDispatcher => {
    const dispatcher = new RouteDispatcher(Site);

    // Auto-discovered routes from @page decorators
    dispatcher.routes = getAllPages();

    return dispatcher;
}

/**
 * Initialize all components found in the DOM
 * Auto-discovers components using @component decorator
 */
export function initializeComponents(): void {
    const componentElements = document.querySelectorAll<HTMLElement>('[sse-component]');

    componentElements.forEach(element => {
        const componentName = element.getAttribute('sse-component');

        if (!componentName) {
            console.warn('Component element found without sse-component value:', element);
            return;
        }

        // Get component from auto-discovered registry
        const ComponentClass = getComponent(componentName);

        if (!ComponentClass) {
            console.warn(\`Unknown component type: "\${componentName}". Did you add the @component decorator?\`, element);
            return;
        }

        try {
            // Instantiate the component
            const componentInstance = new ComponentClass(element);

            // Register with component manager
            window.componentManager.registerComponent(componentName, componentInstance);

            // Execute the component
            componentInstance.exec();
        } catch (error) {
            console.error(\`Error initializing component "\${componentName}":\`, error, element);
        }
    });

    // Log summary
    const totalComponents = window.componentManager.getTotalCount();
    if (totalComponents > 0) {
        console.log(\`Initialized \${totalComponents} component instance(s):\`, window.componentManager.getComponentTypes());
    }
}

/**
 * Log registry statistics
 */
export function logRegistryStats(): void {
    const stats = getRegistryStats();
    console.log(\`[Registry] Discovered \${stats.pages} page(s) and \${stats.components} component(s)\`);
}
`;

  return template;
}

// Run if called directly
if (require.main === module) {
  console.log('🔍 Scanning for @page and @component decorators...');

  const content = generateRoutesFile();
  const { stats } = generateImports();

  fs.writeFileSync('./src/routes.ts', content);

  console.log('✓ Generated routes.ts');
  console.log(`  - ${stats.pages} page(s) found`);
  console.log(`  - ${stats.components} component(s) found`);
}

module.exports = { generateImports, generateRoutesFile };
