/**
 * Route Dispatcher & Module Registry
 * Central location for all pages and components auto-discovery
 *
 * ⚠️ THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated by: generate-imports.js
 * Run: npm run generate:routes
 *
 * https://engine.sygnal.com/
 *
 * ENGINE MODE
 * ?engine.mode=dev
 * ?engine.mode=prod
 */

import { RouteDispatcher } from "@sygnal/sse";
import { Site } from "./site";
import { getAllPages, getComponent, getRegistryStats } from "./engine/registry";

// ============================================================
// PAGES - Auto-discovered (3 found)
// ============================================================
import "./pages/about";
import "./pages/blog";
import "./pages/home";

// ============================================================
// COMPONENTS - Auto-discovered (2 found)
// ============================================================
import "./components/example";
import "./components/test";

/**
 * Create and configure route dispatcher
 */
export const routeDispatcher = (): RouteDispatcher => {
    const dispatcher = new RouteDispatcher(Site);

    // Auto-discovered routes from @page decorators
    dispatcher.routes = getAllPages();

    return dispatcher;
}

/**
 * Initialize all components found in the DOM
 * Auto-discovers components using @component decorator
 */
export function initializeComponents(): void {
    const componentElements = document.querySelectorAll<HTMLElement>('[sse-component]');

    componentElements.forEach(element => {
        const componentName = element.getAttribute('sse-component');

        if (!componentName) {
            console.warn('Component element found without sse-component value:', element);
            return;
        }

        // Get component from auto-discovered registry
        const ComponentClass = getComponent(componentName);

        if (!ComponentClass) {
            console.warn(`Unknown component type: "${componentName}". Did you add the @component decorator?`, element);
            return;
        }

        try {
            // Instantiate the component
            const componentInstance = new ComponentClass(element);

            // Register with component manager
            window.componentManager.registerComponent(componentName, componentInstance);

            // Execute the component
            componentInstance.exec();
        } catch (error) {
            console.error(`Error initializing component "${componentName}":`, error, element);
        }
    });

    // Log summary
    const totalComponents = window.componentManager.getTotalCount();
    if (totalComponents > 0) {
        console.log(`Initialized ${totalComponents} component instance(s):`, window.componentManager.getComponentTypes());
    }
}

/**
 * Log registry statistics
 */
export function logRegistryStats(): void {
    const stats = getRegistryStats();
    console.log(`[Registry] Discovered ${stats.pages} page(s) and ${stats.components} component(s)`);
}
